development:
  adapter: postgresql
  encoding: unicode
  database: whoshouldibench_dev
  pool: 5
  username: postgres 
  password: 1MirPan!

test:
  adapter: postgresql
  encoding: unicode
  database: whoshouldibench_test
  pool: 5
  username: postgres 
  password: 1MirPan!

